version: '3.8'

services:
  ai-agents-sms:
    build: ./ai-agents-sms
    container_name: ai-agents-sms
    expose:
      - "8001"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
  
  ai-cmo:
    build: ./ai-cmo
    container_name: ai-cmo
    expose:
      - "8002"
    environment:
      - AWS_DEFAULT_REGION=us-east-1

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount the letsencrypt directory as read-only
    depends_on:
      - ai-agents-sms
      - ai-cmo
