version: '3.8'
services:
  ai-agents-sms:
    build: ./ai-agents-sms
    container_name: ai-agents-sms
    expose:
      - "8001"
    volumes:
      - ~/.aws:/root/.aws:ro
      
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ai-agents-sms
