version: '3.8'
services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    expose:
      - "80"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi-app
